version: '3.8'

services:
  backend-flask:
    image: gracesumanjali23/lms-backend:2.0.0
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network

  frontend:
    image: gracesumanjali23/lms-frontend:2.0.0
    ports:
      - "80:80"
    depends_on:
      - backend-flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

